---
#Config Playbook
- hosts: spine1,spine2,leaf1,leaf2
  gather_facts: false
  connection: local

  tasks:
    - name: Register global variables
      include_vars:
        file: "{{ lookup('env','PWD') }}/vars/global.yml"
        name: global

    - name: Register interface variables
      include_vars:
        file: "{{ lookup('env','PWD') }}/vars/interface.yml"
        name: interface

    - name: Create configs
      template:
        src: "{{ lookup('env','PWD') }}/templates/full_config.j2"
        dest: "{{ lookup('env','PWD') }}/configs/full_config/{{ inventory_hostname }}_config.cfg"
