name: Sync AVD Server
on:
 push:
   branches:
     - main  #anytime a push is made to the main branch.. This runner wil kickin
 workflow_dispatch:  #optional 


jobs:
 sync_avd:
   runs-on: self-hosted  # Use the self-hosted runner inside your lab


   steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
     - name: Pull Latest Changes on AVD Server
       run: |
         cd /home/arista/sureshk/jinja-yaml-example 
        git pull origin main
